language: python
python:
- '3.8'
install:
- pip install -r requirements.txt
script:
- nose2 -v --with-coverage test
- pylint --output-format=text app
- pylint --output-format=text test
deploy:
- provider: heroku
  api_key:
    secure: 3TghB+sKgBcDH9CMIMyD3NaUbjd5RfJv5zaWxM/eBoMj3mRHZhcDWm1l9CgZLrnq3AAVQv1/LaOdVWSS0K8XD68CQdwffJtc6OYgjk2LWdZpZ6T2/SbHxZU/DKDtGSdO2rW4ft/0lvDaoi8uohi0HplnQUWGfmGfiCMVscao6CwoED8iB8WWQmW8loTbVETYbg9m2DDmpkPVQqubUhKj3MwyqqF1ev8v5B8xbFNtnIYi9hOzJJ3X59ok9yeHFoYTMkchFslyrL36Dyf0jnJb8AS8fyLLhHS2TTb+QM02hsJauGUAgfmW+/I9u3fdEGh9twBmtP4nGq/HfTMfjn/WoWh3Ahe2d8VQaOioxuKsckTe2Fcl0AIFx4VCZ8v0ldWQebuoimgaa+EIU5GPbRDpNf2aOwyiGBfJ3w9Z+UfFlt1pqlwAwkb7QidiqXj3JkqYmbOMI0zDs1afmAHJe6TuTnkKVgBRnxLFDFT/LZFGFXIurbGzT0LOMobgxuCAjaRJgoE/uG+SbaVLmxht8GXsudPS58/H+M2pQ+1WwqiX2ZD+9c5BfopoDkcQM8GA8u5Otn6YfU0J6T37KwBoRny2MahlUh0goLjlMoNeVWwukUC5zzEdh60XR/r/rcAYjxBOOH0rTC1gYHvU1Jo47qxMqzu4lrmYhIU+ZzCHU4U3EDc=
    app: discord-cardbot
