---
language: python
python:
  - '3.8'
install:
  - pip install -r requirements.txt
script:
  - nose2 -v --with-coverage test
  - pylint --output-format=text app
  - pylint --output-format=text test
deploy:
  - provider: heroku
    api_key:
      secure: hghHC4PmEyJp4yvt4wo7cTa9W3hCVhkm88Xt7wK0egzjYMz5ytFizBF0mIS4oCcLa1sLkKXYrbAC4cZmpqIS+FILIzg+dC2o5y41hDoWOcI5swBhv0ZKfPIK/xz982NWl2fgnS56mmf6fM34mYZNE2KDL6z7m+pbHgiUJXv/PC66O0zke5NhedI/bhlgSrbL45W1GDMtIcQeBGTFvcvK2LemwPqkh7RZ4ci/wYeu4Qn+2Jtq84r8C1aGKV/Qf098CEOASYTVVOB8MqYuOLu3gDcMQ+5E3/z+mcJhO/HeE2hi0ia+Pp8YDmNlDMwW19Xf82+WszDzSKSmKOcYO3YPWdRA7p6N4iCJrK4IZDbmzAMUBptg4kz9OR0fSY4nKI8noVgYMFrDhke7m3ywhMRJkC2m/Kcgl1uWI1jEhugRTcM0Z45dHkphyylwAdH5idzqAeeuuwMzeU8aw0Uj8IzeaWkxRVDqTvrnUuEHEXXf0QLvQqAPgwFjG1zmU44GRkZ+iFiteY+VYYuUJMN7ROAKZJYou6re2IK8nsH2keEp37YKFt8aEpSr6I979DyIV1Edc7ltPXRm9N9spQ4abCU83pDiLPAu9QmID8Bv+KldirNQUf2NnjDx1LveOHOF9Ds4e3UA5OeC47sUQlxz70ilbTN2cuU+ixFYQ8E2wfdKElo=
      app: discord-cardbot
