name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install
      - name: Lint app
        run: pipenv run pylint --output-format=text app
      - name: Lint tests
        run: pipenv run pylint --output-format=text tests
      - name: Unit tests
        run: coverage run -m pipenv run nose2 tests
      - name: Generate coverage report
        run: coverage xml
      - name: Upload code coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
